//
//  Constants.swift
//  E-Mistri
//
//  Created by gurzu on 27/12/2022.
//

import Foundation

struct Images {
    static let CurvedBottomImage = "CurvedBottomImage"
    static let VehicleMechanic = "VehicleMechanic"
    static let CallMechanic = "CallMechanic"
    static let GettingStarted = "GettingStarted"
    static let EMistriLogo = "EMistriLogo"
    static let backButton = "arrow.backward.circle"
    static let emptyCheckbox = "emptyCheckbox"
    static let filledCheckbox = "filledCheckbox"
    static let chevronForward = "chevron.forward"
    static let RoundedButtonImage = "chevron.forward"
    static let sortButtonImage = "sortButtonImage"
    static let castrolJar = "castrolJar"
    static let searchBarImagge = "magnifyingglass"
    static let productCategoryBike = "bike"
    static let productCategoryScooty = "scooty"
    static let productCategoryCar = "car"
    static let productCategoryAccessories = "accessories"
    static let brealkPad = "breakPad"
    static let engineFilter = "engineFilter"
    static let gearBox = "gearBox"
    static let rewardPointRibbon = "rewardPointRibbon"
    static let profileImage = "profileImage"
    static let checkmarkImage = "checkmarkImage"
    static let aboutusImage = "aboutusImage"
    static let personImage = "personImage"
    static let settingImage = "settingImage"
    static let shareImage = "shareImage"
    static let logoutImage = "logoutImage"
    static let chevronBackward = "chevron.backward"
    static let favourite = "heart"
    static let heartFill = "heart.fill"
    static let commentBtnImage = "comments"
    static let cartImg = "cart"
    static let star = "star.fill"
    static let substractQuantity = "substractQuantity"
    static let addQuantity = "addQuantity"
    static let closeCellImage = "closeImage"
    static let addIcon = "addIcon"
    static let addImage = "addImage"
    static let changelanguageImage = "changeLanguageImage"
    static let changePasswordImage = "changePasswordImage"
    static let privacyPolicyImage = "privacyPolicyImage"
    static let notificationImage = "notificationImage"
    static let themeImage = "themeImage"
    static let passwordHide = "passwordHide"
    static let passwordShow = "passwordShow"
    static let changePhotoImage = "changePhotoImage"
    static let noUserImage = "noUserImage"
}

struct Text {
    static let titleTextFirstOnboardingScreen = "Solving all your motoworld problems"
    static let bodyTextFirstOnboardingScreen = "Use E-mistri to call for best service near you."
    static let titleTextSecondOnboardingScreen = "On your service within few taps"
    static let bodyTextSecondOnboardingScreen = "E-mistri is on your service within few taps."
    static let titleTextThirdOnboardingScreen = "Let’s get started with E-mistri"
    static let bodyTextThirdOnboardingScreen = "Let us have a new moto servicing experience with E-mistri."
    static let welcomeText = "Welcome Back"
    static let loginScreenSecondaryText = "There are many variations of passages"
    static let usernameTextField = "Email/ Mobile Number"
    static let passWordTextField = "Password"
    static let newAccountText = "Create a New Account"
    static let signupScreenSecondaryText = "There are many variations of passages of Lorem Ipsum available"
    static let agreementText = "I agree with the Terms of Service & Privacy Policy."
    static let dontHaveAccount = "Don’t have an account?"
    static let joinUs = "Join Us"
    static let alreadyHaveAccount = "Already have an Account?"
    static let signin = "Signin"
    static let agreementUrl = "https://www.google.com"
    static let searchTextFieldText = "Search for the products"
    static let carouselTitleText = "Castrol Magnatec"
    static let carouselSecondaryText = "Non-stop Protection From Every Start"
    static let buyNowBtnTitle = "Buy Now"
    static let productCategoryBike = "Bike"
    static let productCategoryCar = "Car"
    static let productCategoryScooty = "Scooty"
    static let productCategoryAccessories = "Accessories"
    static let rewardPointsText = "Reward Points"
    static let profileName = "Jenny Wilson"
    static let profileEmail = "example@gmail.com"
    static let rewardPoints = "38.57"
    static let profileNavigationMyInformation = "My information"
    static let profileNavigationMyInformationSubText = "View your personal information."
    static let profileNavigationSettings = "Settings"
    static let profileNavigationSettingsSubText = "Change your app settings"
    static let profileNavigationShare = "Share"
    static let profileNavigationShareSubText = "Lorem Ipsum available"
    static let profileNavigationAboutUs = "About us"
    static let profileNavigationAboutUsSubText = "Lorem Ipsum available"
    static let logoutText = "Logout"
    static let logoutSubText = "Lorem Ipsum available"
    static let conformationText = "Are you sure you want to logout"
    static let shopScreenTitle = "All Products"
    static let toCartText = "Add to cart"
    static let prodType: String = "BREAK PAD"
    static let prodRating: String = "(4.5)"
    static let prodName: String = "FZ Break Pad"
    static let prodPrice: String = "Rs. 1,999"
    static let prodDescription: String =
        "Amet minim mollit non deserunt ullamco est sit aliqua dolor do amet sint.... See More"
    static let similarProducts = "Similar to this"
    static let cartScreenTitle = "Shopping Cart"
    static let addLabel = "Save Rs 324 compared to Authorised Services"
    static let currentPassword = "CurrentPassword"
    static let newPassWord = "New Password"
    static let confirmPassword = "Confirm Password"
    static let forgotPasswordButton = "Forgot Password?"
    static let changePasswordPlaceholder = "••••••••••••••••"
    static let saveChanges = "Save Changes"
    static let changePhoto = "Change Photo"
    static let tokenHeader = "Authorization"
    static let userKey = "currentUser"
    static let defaultPhoneNumber = "0000000000"
    static let noItemText = "There are no items in you cart"
    
}

struct FontSize {
    static let titleFontSize = CGFloat(35)
    static let loginScreenTitleFontSize = CGFloat(30)
    static let loginScreenSecondaryTextFontSize = CGFloat(20)
}

struct Storyboards {
    static let OnBoardingScreens = "OnBoardingScreens"
    static let LoginAndSignupScreen = "LoginAndSignupScreen"
    static let DashboardScreen = "DashboardScreen"
    static let ProductDetailScreen = "ProductDetails"
    static let ProfileScreen = "ProfileScreen"
    static let settingScreen = "SettingsScreen"
    static let ChangePasswordScreen = "ChangePasswordScreen"
    static let EditProfileScreen = "EditProfileScreen"
    static let MyCartScreenStoryBoard = "MyCartScreen"
}

struct ErrorMessages {
    static let emptyEmailTextField = "Enter email address"
    static let incorrectPassword = "Incorrect Password"
    static let invalidEmailAddress = "Invalid email Address"
    static let atleastOneUppercase = "Password must have atleast one uppercase"
    static let atleastOneSpecialCharacter = "Password must contain one special characters '!@#$&*'"
    static let atleastOneNumber = "Password must contain one number"
    static let lowercaseLetter = "Lower case letter needed"
    static let atleastEightCharacter = "Password must atleast be of 8 characters"
    static let matchPassword = "Password doesn't match"
    static let passwordIsOkay = "Password is okay"
    static let alertText = "Please agree with our Terms of Service & Privacy Policy"
    static let emptyPasswordField = "Password field is empty"
    static let invalidUserName = "Invalid Username"
    static let invalidPhoneNumber = "Invalid phone number"
}

struct ApiURL {
    static let baseURL: String = "https://44d2-103-41-172-114.in.ngrok.io"
    static let signUpURL: String = "\(baseURL)/customers"
    static let signInURL: String = "\(baseURL)/customers/sign_in"
    static let signOutURL: String = "\(baseURL)/customers/sign_out"
    static let editProfileURL: String = "\(baseURL)/api/v1/customers/"
    static let editDisplayPictureURL: String = "\(baseURL)/api/v1/customers/attach_picture"
    static let getProductsList: String = "\(baseURL)/api/v1/products"
}
